{{- if $.Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}-auth
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ default "" .Values.auth.rootPassword | b64enc | quote }}
  {{- if eq $.Values.architecture "group-replication" }}
  MYSQL_REPL_USER: {{ default "" .Values.auth.replicationUser | b64enc | quote }}
  MYSQL_REPL_PASSWORD: {{ default "" .Values.auth.replicationPassword | b64enc | quote }}
  MYSQL_MONITOR_USER:  {{ default "" .Values.proxySQL.auth.monitorUsername | b64enc | quote }}
  MYSQL_MONITOR_PASSWORD:  {{ default "" .Values.proxySQL.auth.monitorPassword | b64enc | quote }}
  {{- end }}
{{- end }}
