{{- if $.Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.name" . }}-script
  namespace: {{ $.Release.Namespace }}
data:
  mysql_manage.sh: |
{{ (.Files.Glob "files/mysql_manage.sh").AsConfig | indent 2 }}
{{- end }}