apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  ROOT_PASSWORD: {{ include "mysql.auth.root.password" . }}
  MYSQL_USER: {{ include "mysql.auth.username" . }}
  MYSQL_PASS: {{ include "mysql.auth.password" . }}
  {{- if eq .Values.global.architecture "group-replication" }}
  REPL_USER: {{ include "mysql.auth.replication.username" . }}
  REPL_PASS: {{ include "mysql.auth.replication.password" . }}
  MONITOR_USER: {{ include "proxysql.auth.monitor.username" .  }}
  MONITOR_PASS: {{ include "proxysql.auth.monitor.password" . }}
  PROXYSQL_USER: {{ include "proxysql.auth.admin.username" . }}
  PROXYSQL_PASS: {{ include "proxysql.auth.admin.password" . }}
  {{- end }}

