{{- if $.Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.mysql.secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  {{- if eq $.Values.architecture "standalone" }}
  MYSQL_HOST: {{ (printf "%s-0.%s" (include "mysql.name" .) (include "mysql.name" .)) | b64enc | quote }}
  MYSQL_PORT: {{ default "" .Values.service.externalPort | toString | b64enc | quote }}
  MYSQL_USER: {{ default "" .Values.auth.username | b64enc | quote }}
  MYSQL_PASS: {{ default "" .Values.auth.password | b64enc | quote }}
  {{- else if eq $.Values.architecture "group-replication" }}
  MYSQL_HOST: {{ (printf "%s-proxysql" (include "mysql.name" .) ) | b64enc | quote }}
  MYSQL_PORT: {{ default "" .Values.proxySQL.service.externalPort | toString | b64enc | quote }}
  MYSQL_USER: {{ default "" .Values.auth.username | b64enc | quote }}
  MYSQL_PASS: {{ default "" .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
