apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  ROOT_PASSWORD: {{ default "" .Values.auth.rootPassword | b64enc | quote }}
  REPL_USER: {{ default "repl" .Values.auth.replicationUser | b64enc | quote }}
  REPL_PASS: {{ default "" .Values.auth.replicationPassword | b64enc | quote }}
  {{- if eq .Values.architecture "group-replication" }}
  MONITOR_USER: {{ default "monitor" .Values.global.auth.monitorUsername | b64enc | quote }}
  MONITOR_PASS: {{ default "" .Values.global.auth.monitorUsername | b64enc | quote }}
  {{- end }}
  MYSQL_USER: {{ default "" .Values.global.auth.username | b64enc | quote }}
  MYSQL_PASS: {{ default "" .Values.global.auth.password | b64enc | quote }}
