apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.mysql }}
      targetPort: mysql
      protocol: TCP
      name: mysql
      {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{.Values.service.nodePort}}
      {{- end }}
    {{- if eq .Values.architecture "group-replication" }}
    - port: {{ .Values.service.ports.group }}
      targetPort: group
      name: group
    {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  publishNotReadyAddresses: true
  clusterIP: None