{{- if and ($.Values.enabled) (eq $.Values.architecture "group-replication") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}-proxysql
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxySQL.service.type }}
  ports:
    - port: {{ .Values.proxySQL.service.externalPort }}
      targetPort: {{ .Values.proxySQL.service.internalPort }}
      protocol: TCP
      name: http
      {{- if contains "NodePort" .Values.proxySQL.service.type }}
      nodePort: {{.Values.proxySQL.service.nodePort}}
      {{- end }}
  selector:
    app.kubernetes.io/name: proxysql
  publishNotReadyAddresses: true
{{- end }} 