apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.mysql }}
    targetPort: {{ .Values.service.ports.mysql }}
    protocol: TCP
    name: {{ .Values.service.portsName.mysql }}
    {{- if contains "NodePort" .Values.service.type }}
    nodePort: {{.Values.service.nodePorts.mysql}}
    {{- end }}
    {{- if eq .Values.architecture "group-replication" }}
  - port: {{ .Values.service.ports.group }}
    targetPort: {{ .Values.service.ports.group }}
    protocol: TCP
    name: {{ .Values.service.portsName.group }}
    {{- if contains "NodePort" .Values.service.type }}
    nodePort: {{.Values.service.nodePorts.group}}
    {{- end }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
  clusterIP: None